### PR TITLE
fix: Android bitmap loader exception

### LINKED ISSUE #168: Splat.BitmapLoader.Current is always null
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Splat.BitmapLoader.Current is always null in Android as seen on issue 57  https://github.com/reactiveui/splat/issues/57

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Using Android 4.4 or 5.0, Visual Studio 2017 or 2015, Splat.BitmapLoader.Current is always null, an exception is always thrown whenever called (it works as expected on Windows). Tried on 3 different computers. Demo project attached.

**What is the expected behavior?**
Splat.BitmapLoader.Current should not be null nor an exception should be thrown.

**What is the motivation / use case for changing the behavior?**
Fixing the bug.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
Splat 2.0.0, 1.6, 1.4. Android 4.4 and 5.0. Visual Studio 2015 and 2017. Could it be related to using an old Android version?
BTW: check your spelling here: "Did this work in previous versions of ReativeUI" => missing "C" at "ReativeUI"

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
A demo project is attached. The execution fails when the following line is reached (MainActivity.cs line 43)
`var bmploader = BitmapLoader.Current; //null error`

[SplatTest.zip](https://github.com/reactiveui/splat/files/1739646/SplatTest.zip)

### PR DESCRIPTION
**Pull request by cabauman**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
fixes #168

**What is the current behavior? (You can also link to an open issue here)**
Null reference exception

**What is the new behavior (if this is a feature change)?**
No exception

**What might this PR break?**
Nothing

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

File: src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs [hunk 1]
```diff
@@ -28,11 +28,15 @@ static PlatformBitmapLoader()
         {
             // NB: This is some hacky shit, but on MonoAndroid at the moment,
             // this is always the entry assembly.
-            var assm = AppDomain.CurrentDomain.GetAssemblies()[1];
-
-            var resources = assm.GetModules().SelectMany(x => x.GetTypes()).First(x => x.Name == "Resource");
-
-            _drawableList = resources.GetNestedType("Drawable").GetFields()
+            var assembly = AppDomain.CurrentDomain.GetAssemblies()[1];
```
Comment (RLittlesII) [inline src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs]: Can we change the array syntax?

File: src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs [hunk 2]
```diff
@@ -69,6 +74,11 @@ public async Task<IBitmap> Load(Stream sourceStream, float? desiredWidth, float?
         /// <inheritdoc />
         public Task<IBitmap> LoadFromResource(string source, float? desiredWidth, float? desiredHeight)
         {
+            if (_drawableList == null)
```
Comment (RLittlesII) [inline src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs]: What is the current behavior here if this case wasn't caught?  Is this potentially a breaking change?

Comment (cabauman) [reply src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs]: Not a breaking change. The current behavior is that the user doesn’t even get a chance to call the method. Because it crashes in the constructor when accessing BitmapLoader.Current.

File: src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs (hunk 1 above)
Comment (cabauman) [reply src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs]: What would you like to change it to?

Comment (glennawatson) [reply src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs]: Could do `AppDomain.CurrentDomain.GetAssemblies().Skip(1).FirstOrDefault()` -- like the comment says pretty hacky regardless.

File: src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs [hunk 3]
```diff
@@ -44,7 +48,8 @@ public async Task<IBitmap> Load(Stream sourceStream, float? desiredWidth, float?
 
             if (desiredWidth == null)
             {
-                bitmap = await Task.Run(() => BitmapFactory.DecodeStream(sourceStream)).ConfigureAwait(true);
+                sourceStream.Position = 0;
```
Comment (glennawatson) [inline src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs]: You may want to move that `sourceStream.Position = 0` to outside the if statement. I suspect both cases may benefit from it being set back to the beginning.

File: src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs (hunk 1 above)
Comment (glennawatson) [reply src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs]: Oh and also if you don't mind, lets not have swearing in our comments if we can help it I guess. Just change it to hacky ;0

Comment (RLittlesII) [reply src/Splat/Platforms/Android/Bitmaps/PlatformBitmapLoader.cs]: Yeah.  It just felt odd looking at the code seeing the array syntax and then right below it the linq syntax.  Might as well clean it up while we are in here.
