### PR TITLE
fix: reuse resolver instead of re-instantiating it

### LINKED ISSUE #378: bug: RxUI.EnsureInitialized called after DI container locked
**Describe the bug**
MSDI provides IoC in two stages, registration and resolution, once the provider has been built, services can no longer be added.
The problem is that RxUI does attempt to add new services after building of container.
TBH, wasn't sure where to post this issue on Rx or Splat.

**Steps To Reproduce**
- Install `Splat.Microsoft.Extensions.DependencyExtensions`
- Install RxUI
setup your app as follows:
```c#
void Init()
{
  //var location = Assembly.GetExecutingAssembly().Location;
  //var configFile = ExtractResource("Aqounts.appsettings.json", location);

  var host =
    Host
    .CreateDefaultBuilder()
    .ConfigureServices(services =>
    {
      services.UseMicrosoftDependencyResolver();
      // Configure local services and access the host configuration
      ConfigureServices(services);
    })
    .ConfigureLogging(loggingBuilder =>
    {
      // remove loggers incompatible with UWP
      {
        var eventLoggers = loggingBuilder.Services
          .Where(l => l.ImplementationType == typeof(EventLogLoggerProvider))
          .ToList();

        foreach (var el in eventLoggers)
          loggingBuilder.Services.Remove(el);
      }

      loggingBuilder.AddSplat();
    })
    .UseEnvironment(Environments.Development)
    .Build();

  //Save our service provider so we can use it later.
  Container = host.Services;
  Container.UseMicrosoftDependencyResolver();
}
```

In one of the following scenes, execute an observable which internally trigger one of the static constructors that attempts to register services.

**Solutions**
1. Silently ignore the new registrations
2. Ensure RxUI runs all service registrations when `UseMicrosoftDependencyResolver(IServiceCollection)` is called, and only if not `HasRegistration(contract)` (related: #372) - preferred and proper solution.

### PR DESCRIPTION
**Pull request by weitzhandler**
Fixes #378.

### CODE REVIEW

File: src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs [hunk 1]
```diff
@@ -71,6 +63,22 @@ protected virtual IServiceProvider ServiceProvider
...
+        /// <param name="serviceProvider">A ready to use service provider.</param>
+        public void UpdateContainer(IServiceProvider serviceProvider)
+        {
+            if (serviceProvider == null)
+            {
+                throw new ArgumentNullException(nameof(serviceProvider));
+            }
+
+            _serviceCollection = null;
+            _serviceProvider = serviceProvider;
```
Comment (glennawatson) [inline src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs]: You may need to use a lock() around the _serviceProvider since this is definitely not going to be thread safe. 

You are doing about 3 operations there so don't think it can be avoided.

Comment (weitzhandler) [reply src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs]: Will this suffice?

```c#
public void UpdateContainer(IServiceProvider serviceProvider)
{
    lock (_syncLock)
    {
        if (serviceProvider == null)
        {
            throw new ArgumentNullException(nameof(serviceProvider));
        }

        _serviceCollection = null;
        _isImmutable = true;
        _serviceProvider = serviceProvider;
    }
}
```

Comment (weitzhandler) [reply src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs]: Will this suffice?

```c#
public void UpdateContainer(IServiceProvider serviceProvider)
{
    if (serviceProvider == null)
    {
        throw new ArgumentNullException(nameof(serviceProvider));
    }

    lock (_syncLock)
    {

        _serviceCollection = null;
        _serviceProvider = serviceProvider;
        _isImmutable = true;
    }
}
```

File: src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs [hunk 2]
```diff
@@ -64,13 +57,38 @@ protected virtual IServiceProvider ServiceProvider
...
+                    lock (_syncLock)
+                    {
+                        if (_serviceProvider == null)
+                        {
+                            _serviceProvider = _serviceCollection.BuildServiceProvider();
+                        }
+                    }
                 }
 
                 return _serviceProvider;
```
Comment (weitzhandler) [inline src/Splat.Microsoft.Extensions.DependencyInjection/MicrosoftDependencyResolver.cs]: I'm thinking maybe this part should also be synced because while this method is called and `_serviceProvider` is not null, it could be refreshed (by nulling it) in other methods.
Gonna update.
